{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nexus-iq.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $fullName }}
  labels:
{{ include "nexus-iq.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostName| quote }}
      http:
        paths:
          - backend:             
              serviceName: {{ .Values.service.name }} ##this needs to match the name of the service being deployed. 
              servicePort: {{.Values.service.port}}
            path: /
{{- end }}