{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.service.name }}
  labels:
{{ include "nexus-iq.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{.Values.service.portName}}
      port: {{ .Values.service.port }}
      targetPort: {{.Values.service.port}}
      protocol: TCP
  selector:
    app: {{ template "nexus-iq.name" . }}
    release: {{ .Release.Name }}
{{- end}}